---
- name: Install apt packages and Docker on Ubuntu server (aarch64 architecture)
  hosts: standalone
  become: yes
  vars:
    apt_packages:
      - git
      - net-tools
    docker_compose_version: "2.28.1"  # You can specify the version you need here

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install specified apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages }}"

    - name: Install prerequisite packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-aarch64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create symbolic link for Docker Compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version_output

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version installed: {{ docker_compose_version_output.stdout }}"