---
- name: Reboot
  hosts: all
  gather_facts: true
  tasks:
    - name: Reboot the nodes (and Wait up to 5 mins max)
      become: true
      reboot:
        reboot_command: "{{ custom_reboot_command | default(omit) }}"
        reboot_timeout: 300
